### ISSUE TITLE
librass_gis.7.2.0.dll not found

### ISSUE THREAD

**Issue by tim-salabim** [r-spatial/link2GI#1]
I can't seem to inititlise `rgrass7` with `link2GI`

```r
> library(link2GI)
> 
> grs <- searchGRASSW()

searching for GRASS installations - this may take a while
For providing the path manually see ?searchGRASSW 
> grs
                             instDir         version installationType
1 C:\\Program Files\\GRASS GIS 7.2.0 GRASS GIS 7.2.0             NSIS
2             C:\\PROGRA~1\\QGISPI~1     grass-6.4.3          osgeo4W
> setGrassEnv4W(grassRoot = grs[1, 1], 
+               grassVersion = grs[1, 2],
+               installationType = grs[1, 3], 
+               jpgmem = 1e+06)
[1] "C:\\Program Files\\GRASS GIS 7.2.0"
> 
> setwd("~/")
> 
> library(rgrass7)
Error in if (file.exists(file) == FALSE) if (!missing(asText) && asText ==  : 
  argument is of length zero
In addition: Warning message:
running command 'g.version.exe --interface-description' had status 309 
Error : .onAttach in attachNamespace() für 'rgrass7' fehlgeschlagen, Details:
  Aufruf: parseGRASS(cmd, legacyExec = legacyExec)
  Fehler: g.version not parsed
Error: Laden von Paket oder Namensraum für ‘rgrass7’ fehlgeschlagen
```
causes error popup saying that libgrass_gis.7.2.0.dll is missing from the computer. However,
```r
file.exists("C:/Program Files/GRASS GIS 7.2.0/lib/libgrass_gis.7.2.0.dll")
[1] TRUE
```
my sessionInfo()

```r
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] XML_3.98-1.5  sp_1.2-4      link2GI_0.1-0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9       lattice_0.20-34   codetools_0.2-15  sf_0.3-0          foreach_1.4.3     R.methodsS3_1.7.1 grid_3.3.2        DBI_0.5-1        
 [9] units_0.4-2       raster_2.5-8      R.oo_1.21.0       R.utils_2.5.0     rgdal_1.2-5       iterators_1.0.8   tools_3.3.2       gdalUtils_2.0.1.7
[17] udunits2_0.13     rgrass7_0.1-9
```
Any ideas?

**Comment by gisma** [comment]
Yup I am working on this. It is a defined Win7 GRASS standalone installation issue. Probably as simple as a multi-language  mapping problem of the path string.   Will solve it asap.

**Comment by tim-salabim** [comment]
If it helps, I see in the `PATH` variable of `Sys.getenv()`:
`C:\Program Files\GRASS GIS 7.2.0\apps\grass\GRASS GIS 7.2.0\lib`
while the `apps` subfolder does not exist on my machine. The correct path value should be 
`C:/Program Files/GRASS GIS 7.2.0/lib`

**Comment by gisma** [comment]
I am running Linux at the moment. Basically it should work if you call `linkGRASS7()` with the results of your  `searchGRASSW()` call as follows:
`r<-raster("file.tif")`
`linkGRASS7(c("C:\\Program Files\\GRASS GIS 7.2.0", "GRASS GIS 7.2.0","NSIS"), r)`

**Comment by gisma** [comment]
Did help a lot :-). It seems to be a bit more complicated than I thought...
I tried to fix this in a first dirty hack. Could you please try the code example?
`library(sp)`
`data(meuse)` 
`coordinates(meuse) <- ~x+y `
`proj4string(meuse) <-CRS("+init=epsg:28992") `
`linkGRASS7(meuse)`

**Comment by tim-salabim** [comment]
Now the error popup states that `iconv.dll` is missing (several times - had to click 'OK' about 8 times).
Console output afterwards:
```r
Error in if (!compatible) { : argument is of length zero
In addition: There were 11 warnings (use warnings() to see them)

> warnings()
Warnmeldungen:
1: running command 'g.dirseps.exe -g "junk"' had status 309
2: running command 'g.dirseps.exe -g "C:\Users\TIM~1.APP\AppData\Local\Temp\RtmpM70Rmn"' had status 309
3: running command 'g.gisenv.exe "set=GISDBASE= NA"' had status 309
4: In dir.create(loc_path) :
  cannot create dir 'NA\file20c87cb510f9', reason 'No such file or directory'
5: In dir.create(paste(loc_path, "PERMANENT", sep = "/")) :
  cannot create dir 'NA\file20c87cb510f9\PERMANENT', reason 'No such file or directory'
6: In dir.create(paste(loc_path, mapset, sep = "/")) :
  cannot create dir 'NA\file20c87cb510f9\PERMANENT', reason 'No such file or directory'
7: running command 'g.gisenv.exe "set=GISDBASE=NA"' had status 309
8: running command 'g.gisenv.exe "set=LOCATION_NAME=file20c87cb510f9"' had status 309
9: running command 'g.gisenv.exe "set=MAPSET=PERMANENT"' had status 309
10: running command 'g.gisenv.exe "set=GRASS_GUI=text"' had status 309
11: running command 'g.version.exe' had status 309
```

**Comment by gisma** [comment]
Thanks for sharing this - big step forward because this looks like interfering (or less probably) missing Microsoft Visual C++ Runtime Libraries. And you have to click for each 309 error ;-)

I think there is more than one  GDAL installation available through the systems  `%PATH%` variable so that they will interfer. This can also happen If you call `linkGRASS7()` several times with different options it will not clean up the session `%PATH%` variable.  Please check the sessions `%PATH%` content. 
Maybe restarting the session helps also.

**Comment by tim-salabim** [comment]
Actually, very probably it is the missing Microsoft Visual C++ Runtime Libraries, as their download fails and GRASS is installed without them. That's what I meant with a possible proxy issue earlier. I saw that the PATH variable is not cleaned when calling `linkGRASS7` many times, but in the case above I only called it once. 

I'll see if I can get the C++ Visual libraries installed and then report back whether things work as expected.

**Comment by tim-salabim** [comment]
Turns out that on a local machine (i.e. not part of our network) with direct internet access (no proxy) and complete installation (Microsoft Visual C++ Runtime Libraries installed) we get the same `iconv.dll` error(s)

**Comment by gisma** [comment]
AFAIK GRASS respective GDAL want's their own Microsoft Visual C++ Runtime Libraries. It is also packed with the GRASS standalone version. I will try to add the correct folders to the `%PATH%` variable. So  please give another try.

**Comment by tim-salabim** [comment]
Setting the missing Microsoft Visual C++ Runtime Libraries aside, the above example (`linkGRASS7(meuse)`) now works with the latest patch. Thanks!
