### ISSUE TITLE
Issue with findOTB()/linkOTB

### ISSUE THREAD

**Issue by goergen95** [r-spatial/link2GI#13]
Eventhoug path to the OTB dir is given to the functions, an error occurs stating:

Error in data.frame(binDir = root_dir, baseDir = installDir, installation_type = installerType,  : 
  object 'root_dir' not found

My sessionInfo:

R version 3.4.3 (2017-11-30) Platform: x86_64-w64-mingw32/x64 (64-bit) 
Running under: Windows >= 8 x64 (build 9200)  

Matrix products: default  locale: [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 [4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252      

attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other 

attached packages: [1] mapview_2.6.0 link2GI_0.3-5 raster_2.7-15 rgdal_1.3-6   sp_1.3-1      

 loaded via a namespace (and not attached):  [1] Rcpp_0.12.19       lattice_0.20-35    FNN_1.1.2.1        png_0.1-7          prettyunits_1.0.2  class_7.3-14        [7] ps_1.2.0           zoo_1.8-4          assertthat_0.2.0   gstat_1.1-6        rprojroot_1.3-2    digest_0.6.18      [13] foreach_1.4.4      mime_0.6           R6_2.3.0           plyr_1.8.4         backports_1.1.2    stats4_3.4.3       [19] e1071_1.7-0        rlang_0.3.0.1      rstudioapi_0.8     callr_3.0.0        R.utils_2.7.0      R.oo_1.22.0        [25] desc_1.2.0         devtools_2.0.1     webshot_0.5.1      stringr_1.3.1      foreign_0.8-69     htmlwidgets_1.3    [31] munsell_0.5.0      shiny_1.2.0        compiler_3.4.3     httpuv_1.4.5       shapefiles_0.7     rgrass7_0.1-12     [37] base64enc_0.1-3    pkgbuild_1.0.2     htmltools_0.3.6    roxygen2_6.1.0     intervals_0.15.1   codetools_0.2-15   [43] XML_3.98-1.16      viridisLite_0.3.0  spacetime_1.2-2    later_0.7.5        crayon_1.3.4       withr_2.1.2        [49] sf_0.7-1           R.methodsS3_1.7.1  commonmark_1.6     grid_3.4.3         satellite_1.0.1    xtable_1.8-3       [55] spData_0.2.9.4     RSAGA_1.2.0        DBI_1.0.0          magrittr_1.5       scales_1.0.0       units_0.6-1        [61] cli_1.0.1          stringi_1.1.7      promises_1.0.1     fs_1.2.6           remotes_2.0.2      leaflet_2.0.2      [67] testthat_2.0.1     xml2_1.2.0         xts_0.11-1         iterators_1.0.10   tools_3.4.3        gdalUtils_2.0.1.14 [73] glue_1.3.0         crosstalk_1.0.0    processx_3.2.0     pkgload_1.0.2      yaml_2.2.0         colorspace_1.3-2   [79] sessioninfo_1.1.0  classInt_0.2-3     memoise_1.1.0      usethis_1.4.0

Any idea what might be wrong?

**Comment by gisma** [comment]
Thanks for reporting. I am not able to reproduce it under Win7 and Win10. Please provide the exact call with all arguments and please also provide the output from the cmd line call  `dir C:\otbcli.bat /B /S`

**Comment by goergen95** [comment]
findOTB("C:/Program Files/OTB-6.6.0-Win64/")

Error in data.frame(binDir = root_dir, baseDir = installDir, installation_type = installerType,  : 
  object 'root_dir' not found

linkOTB("C:/Program Files/OTB-6.6.0-Win64/")

Error in data.frame(binDir = root_dir, baseDir = installDir, installation_type = installerType,  : 
  object 'root_dir' not found

the output of the call you asked for is: 
C:\$Recycle.Bin\S-1-5-21-27387793-1785775987-1783778107-1002\$RANN4GW.0-Win64\bin\otbcli.bat

**Comment by gisma** [comment]
please empty your recycle bin and deinstall OTB from your system. Adter doing so please install the zipped [OTB binaries](https://www.orfeo-toolbox.org/packages/OTB-6.6.0-Win64.zip) and unzip them to an appropriate folder. 
Finally please rerun the `dir C:\otbcli.bat /B /S` command

**Comment by goergen95** [comment]
It worked! Thank you :)
