### ISSUE TITLE
linkOTB( ) more than one version downloaded

### ISSUE THREAD

**Issue by ghost** [r-spatial/link2GI#16]
There are two identical versions of Orfeo toolbox on my pc but located in different folders. When I execute link2GI:linkOTB( ) an error is printed and neither of the both versions is linked.

> link2GI::findOTB("C:/Users/Ben/Downloads/")
                                                              binDir                                                     baseDir
1 C:\\Users\\Ben\\Downloads\\OTB-6.6.0-Win64\\OTB-6.6.0-Win64\\bin\\ C:\\Users\\Ben\\Downloads\\OTB-6.6.0-Win64\\OTB-6.6.0-Win64
  installation_type
1                  
> link2GI::findOTB()
                                                                                          binDir
1 C:\\Users\\Ben\\Documents\\Studium\\02_Master\\03_GIS\\OTB-6.6.0-Win64\\OTB-6.6.0-Win64\\bin\\
2                             C:\\Users\\Ben\\Downloads\\OTB-6.6.0-Win64\\OTB-6.6.0-Win64\\bin\\
                                                                                  baseDir installation_type
1 C:\\Users\\Ben\\Documents\\Studium\\02_Master\\03_GIS\\OTB-6.6.0-Win64\\OTB-6.6.0-Win64               OTB
2                             C:\\Users\\Ben\\Downloads\\OTB-6.6.0-Win64\\OTB-6.6.0-Win64               OTB
> link2GI::linkOTB()
Error in link2GI::linkOTB() : object 'pathOTB' not found
> link2GI::linkOTB(ver_select = 1)
You have more than one valid OTB version
  binDir                                                                                        
1 C:\\Users\\Ben\\Documents\\Studium\\02_Master\\03_GIS\\OTB-6.6.0-Win64\\OTB-6.6.0-Win64\\bin\\
2 C:\\Users\\Ben\\Downloads\\OTB-6.6.0-Win64\\OTB-6.6.0-Win64\\bin\\                            
Please choose one:  1
$`pathOTB`
[1] "C:\\Users\\Ben\\Documents\\Studium\\02_Master\\03_GIS\\OTB-6.6.0-Win64\\OTB-6.6.0-Win64\\bin\\"

$version
                                                                                          binDir
1 C:\\Users\\Ben\\Documents\\Studium\\02_Master\\03_GIS\\OTB-6.6.0-Win64\\OTB-6.6.0-Win64\\bin\\
2                             C:\\Users\\Ben\\Downloads\\OTB-6.6.0-Win64\\OTB-6.6.0-Win64\\bin\\
                                                                                  baseDir installation_type
1 C:\\Users\\Ben\\Documents\\Studium\\02_Master\\03_GIS\\OTB-6.6.0-Win64\\OTB-6.6.0-Win64               OTB
2                             C:\\Users\\Ben\\Downloads\\OTB-6.6.0-Win64\\OTB-6.6.0-Win64               OTB

$exist
[1] TRUE

**Comment by gisma** [comment]
should be fixed? Please reopen if necessary
