### ISSUE TITLE
linkGDAL needs to be re-implemented 

### ISSUE THREAD

**Issue by gisma** [r-spatial/link2GI#17]
linkGDAL is just a small wrapper around the gdalUtils setup function. However there are major problems in adressing alternative pathes and rescanning the system for all installations wich seems to be necessary  especially with respect to the difficult situation around  GDAL binaries.

Due to some weird inter-dependencies of  gdalUtils and GDAL binaries as well as the observation that the current gdal proj4 proj6 situation is a bit confusing. linkGDAL is a full search and linkage to all GDAL at the search location. 

It is meant for API calls via `system/system2 ` 
It will **not** work for `rgdal`, `gdalUtils` and so on.

**Comment by gisma** [comment]
most of the job is done and integrated . needs final tests.

**Comment by aloboa** [comment]
On windows, with
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
link2GI_0.3-6

I get
```
> findGDAL(quiet=FALSE)
Error in data.frame(binDir = root_dir, baseDir = installDir, installation_type = installerType,  : 
  object 'root_dir' not found
> linkGDAL(quiet = FALSE)
Error in data.frame(binDir = root_dir, baseDir = installDir, installation_type = installerType,  : 
  object 'root_dir' not found
(same for OTB)

```
Both return the correct paths on Linux.
But, on linux, according to the manual
"add otb pathes to the enviroment and creates global variables path_OTB"
Nevertheless, I open the Terminal from within RStudio and the pate has not been added to PATH and
path_OTB is empty

**Comment by gisma** [comment]
fixed by version 0.3-6

**Comment by aloboa** [comment]
I still get the same using link2GI_0.3-8:
```
> findGDAL(quiet=FALSE)
Error in data.frame(binDir = root_dir, baseDir = installDir, installation_type = installerType,  : 
  object 'root_dir' not found
```

**Comment by gisma** [comment]
running the current master branch version of `link2GI `   and only one installation of GDAL binaries  (maybe this will explain the issue i will check when back on my developing system) using `OSGEO4w` as installer  I am not able to reproduce this error.
```
SessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)
[....]
```
The result of  `link2GI::findGDAL(quiet = F)`:
 
```
$gdalInstallations
                binDir       baseDir installation_type
1 C:\\OSGeo4W64\\bin\\ C:\\OSGeo4W64     osgeo4w64GDAL

$bin
$bin[[1]]
                                gdal_bin
1      C:/OSGeo4W64/bin/gdal-dev-env.bat
2           C:/OSGeo4W64/bin/gdal300.dll
3      C:/OSGeo4W64/bin/gdal_contour.exe
4         C:/OSGeo4W64/bin/gdal_grid.exe
5    C:/OSGeo4W64/bin/gdal_rasterize.exe
6    C:/OSGeo4W64/bin/gdal_translate.exe
7          C:/OSGeo4W64/bin/gdaladdo.exe
8      C:/OSGeo4W64/bin/gdalbuildvrt.exe
9           C:/OSGeo4W64/bin/gdaldem.exe
10      C:/OSGeo4W64/bin/gdalenhance.exe
11         C:/OSGeo4W64/bin/gdalinfo.exe
12 C:/OSGeo4W64/bin/gdallocationinfo.exe
13       C:/OSGeo4W64/bin/gdalmanage.exe
14          C:/OSGeo4W64/bin/gdalplugins
15       C:/OSGeo4W64/bin/gdalserver.exe
16      C:/OSGeo4W64/bin/gdalsrsinfo.exe
17       C:/OSGeo4W64/bin/gdaltindex.exe
18    C:/OSGeo4W64/bin/gdaltransform.exe
19         C:/OSGeo4W64/bin/gdalwarp.exe


$py
$py[[1]]
[1] gdal_py
<0 Zeilen> (oder row.names mit Länge 0)
```

**Comment by gisma** [comment]
as far I see the `linkGDAL` is implented like the other APIs. So one should be able to search and choose the preferred GDAL binaries.
