### ISSUE TITLE
Error linking GRASS on Arch Linux

### ISSUE THREAD

**Issue by pat-s** [r-spatial/link2GI#26]
On Arch Linux with Grass 7.8 installed from AUR I get

```r
link2GI::linkGRASS7(streets)
Error in gregexpr(pattern = "\"", root_dir)[[1]] : 
  subscript out of bounds
```

Same for

```r
link2GI::searchGRASSX()
Error in gregexpr(pattern = "\"", root_dir)[[1]] : 
  subscript out of bounds
```

both with CRAN and dev version.

Even when specifying the full path I get the error

```r
 link2GI::linkGRASS7(location = "/opt/grass/bin")
Error in gregexpr(pattern = "\"", root_dir)[[1]] : 
  subscript out of bounds
```

**Comment by gisma** [comment]
I was struggling with this a few weeks ago when I switched occasionally to Manjaro. Thought that I have fixed it thanks for reporting that I did not. The problem is that the GRASS people changed their initialisation script naming variables different and using other libs. Asap I will dive in  again .

**Comment by gisma** [comment]
quite a sloppiness and inconsistency of mine I did the recent commits in the master branch... 
Please check the master branch on github. If I do so I get for Manjaro Arch:
After solving #27 Iwill push it asap on CRAN either. 
```r
 link2GI::searchGRASSX()
     instDir version installation_type
1 /opt/grass   7.8.0           grass78
```

**Comment by pat-s** [comment]
Thanks. This works now for, but `link2GI::linkGRASS7()` does not yet

```r
searchGRASSX()
# A tibble: 1 x 3
  instDir    version installation_type
  <chr>      <chr>   <chr>            
1 /opt/grass 7.8.1   grass78    
      
link2GI::linkGRASS7()
Error in rgrass7::execGRASS("g.proj", flags = c("c", "quiet"), proj4 = proj4) : 
  object 'proj4' not found
```

**Comment by gisma** [comment]
still needs some checks
