### ISSUE TITLE
linkSAGA

### ISSUE THREAD

**Issue by jannes-m** [r-spatial/link2GI#3]
library("link2GI")
    library("RSAGA")
    linkSAGA()
    rsaga.env()

This code returns following warning message:

    Warning message:
    In rsaga.env() : Invalid SAGA path C:\OSGeo4W64\apps\saga\

This could be easily fixed by deleting the last backslash in the path to SAGA:

    gsub("\\\\$", "", "C:\\OSGeo4W64\\apps\\saga\\")

**Comment by gisma** [comment]
@jannes-m thanks for advising this. I try to fix this and some more windows issues during the next days for the next CRAN release

**Comment by gisma** [comment]
@jannes-m 

in the current github version it should be fixed. But you have to mention that linkSAGA  is pretty simple (and dirty). It is just looking for the installations of SAGA and returns the location as global variables.
So you should to call `rsaga.env` like following:
```
library("link2GI")
library("RSAGA")
linkSAGA()
rsaga.env(path = sagaPath, modules = sagaModPath)
```
cheers Chris
EDIT 
I have added the global variable 'sagaModPath' in the enviroment . So you may use it if you need the `rsaga.env()` function. 
I am not quite sure but as for me who I am runnig 4 differnt SAGA versions it is a bit cumbersome to integrate full windows environments which would be necessary to inform RSAGA about the special link2GI session. If you think this would be helpful please reopen the issue
cheers Chris

**Comment by jannes-m** [comment]
Hey Chris,
thank you for working on this issue! I have two questions. 

1. It is a bit unusual to write variables/objects into the global environment. Would it be an idea to let `linkSAGA()` return the retrieved paths as a list instead?
2. `linkSAGA()` also modifies the PATH variable (which makes it user-friendly) by adding the SAGA path to it. However, the path still ends with double backslashes (in my case: `C:\\OSGeo4W64\\apps\\saga\\`) which still leads to the annoying Warning message `Warning message:
In rsaga.env() : Invalid SAGA path C:\OSGeo4W64\apps\saga\`. Could you be so kind and change that also, please?

**Comment by gisma** [comment]
Hey Jannes 
ad 1 you are pretty kind using 
> unusual 
It was at this point convenient and it is simple to change it to the conventional way by returning it as a list.
ad 2 will check it again asap.
Would you have concerns if I optionally add a switch if user like to have the path as a global or system variable?

**Comment by jannes-m** [comment]
Well, I think writing sth. in the global environment is always a bit dangerous. Though it might be unlikely, it can happen that the user has already specified an object that you will overwrite. Hence, to be on the safe side, I would always avoid writings sth. into the global environment.

**Comment by gisma** [comment]
Well I write it in an inherited new environment... Nevertheless  I appreciate your well known point. Probably it will have some major changes to my own scripts because they are heavily relying on temporary globals. Would need some programming help how to deal with it....
I will fix it for all link functions.
cheers Chris

**Comment by gisma** [comment]
Hi Jannes,
Actually my approach is dropping the global variables and returning a list containing  `$sagaPath` , `$sagaModPath`  and `$sagaCmd`  and. `$installed ' . The latter provides all installed versions on the system.
```
> library(link2GI)
> saga<-linkSAGA()
> saga
$sagaPath
[1] "C:\\OSGeo4W64\\apps\\saga-ltr"

$sagaModPath
[1] "C:\\OSGeo4W64\\apps\\saga-ltr\\modules"

$sagaCmd
[1] "C:\\OSGeo4W64\\apps\\saga-ltr\\saga_cmd.exe"

$installed
                                        binDir                                             moduleDir installation_type
1                C:\\OSGeo4W64\\apps\\saga-ltr                C:\\OSGeo4W64\\apps\\saga-ltr\\modules     osgeo4w64SAGA
2 C:\\Program Files\\QGIS 2.18\\apps\\saga-ltr C:\\Program Files\\QGIS 2.18\\apps\\saga-ltr\\modules          qgisSAGA
3           C:\\Program Files (x86)\\SAGA-GIS6             C:\\Program Files (x86)\\SAGA-GIS6\\tools          userSAGA
```
Currently the selected version is added to the system path. If you want to initalize `RSAGA` via `rsaga.env` you can do it like this:

``` 
RSAGA::rsaga.env()
```
To override it you may also initialize it like:

```
RSAGA::rsaga.env(path = saga$installed$binDir[3],modules = saga$installed$moduleDir[3])
``` 

@jannes-m if this seems to be ok for you I will use this structure for the whole linking functions.  I cleaned and reorganized some of the most ugliest things and will finish a vignette for a CRAN update to version 0.3-0 

@Robinlovelace @jannes-m  I would suggest that I will update the section of your book with this new and hopefully more straightforward and robust link2GI calls.

**Comment by Robinlovelace** [comment]
Just read this discussion - interesting stuff. Agree with Jannes that creating global vars is unusual. Hidden objects can be created with `.objectName`, e.g. as described [here](http://www.talkstats.com/threads/hiding-objects-in-r.18902/).

I've not looked at the changes, agree programming help could be good (stackoverflow / asking on lists always an option), but by the sounds of it this the changes are definitely and improvement. If you could update the book accordingly that would be fantastic. Many thanks.

**Comment by gisma** [comment]
@jannes-m @Robinlovelace 
I am aware that it is unusual to generate globals. Almost the  same with hiding them.
Never mind. I have rewirten the whole code and every call generates a return with the path params etc and the necessary setting in the system environment. The latter is obligate for the GRASS and OTB stuff and very convinient for RSAGA.
I will adapt the examples in your book as soon as I have pushed it on CRAN.
thanks for appreciationg this.
Chris

**Comment by gisma** [comment]
@jannes-m @Robinlovelace 
I have fixed the known issues of `link2GI`. 

Furthermore, the function calls have been strictly homogenized and some bugs have been fixed. 

I've improved the documentation so that most meaningful calls are reasonably documented  and finally you will find  a basic vignette. 

As far as I see this issue can be closed.

**Comment by jannes-m** [comment]
Perfect, thank you so much for your efforts! I will give it a try!
