### ISSUE TITLE
suppress console output

### ISSUE THREAD

**Issue by raff-k** [r-spatial/link2GI#4]
Hello,

I am very grateful for the function of the packages :-) 
However, is there a possibility to hide the console output of the functions? I.e. using `link2GI::linkGRASS7()` I get some warnings...

I already tried `invisible()`, `suppressMessages()` and `sink()` but it did not work. The warnings are still at the console. In `rgrass7::...` there is the function parameter `Sys_show.output.on.console=FALSE` which can do this job. But, I cannot access it from the functions at the moment.

**Comment by gisma** [comment]
Hi @raff-k 
Sorry for the delay - I was sucked by some other projects. I am working on a major fix and will  try to integrate your issue. Thanks for the hints.
cheers chris

**Comment by gisma** [comment]
@raff-k  I am in the update process to the CRAN version 0.2-0. This is for some major bugs... Hope nothing is breaking your workarounds.
I will furthermore integrate the verbose-mode which is a bit of cumbersome work due to the fact that the system calls are showing different behaviours with the sdtin stdout and error handling depending on the OS you are running . I will try to catch all console outputs in the version 0.2-1 release coming during the next weeks. 
cheers Chris

**Comment by gisma** [comment]
@raff-k actually I am not quite sure what kind of message you want to supress. The only one I force is:
``` link2GI::linkGRASS7()

 Error in link2GI::linkGRASS7() : 
  You MUST provide a raster*, sp* object or manually the extent of the loccation...
 Did not found any of them so stopped.````
is just fiving you the Hint that the initialisation needs any kind of reference. 
cheers Chris

**Comment by gisma** [comment]
added in  cran 0.2-1 you may use know the argument `quiet = TRUE` for suppressing hopefully every console output.

**Comment by raff-k** [comment]
thank you for adding the quiet-parameter :-)

however, regardless of whether I set `quiet = TRUE` or not,  the following message appears:

>                 -={ OSGeo4W Shell Commands }=-
> Syntaxfehler.
>         
>         
>         
> 
> GDAL 2.2.3, released 2017/11/20

... but all is working ;-)

**Comment by gisma** [comment]
thanks for providing. could you please provide sessionInfo and what version  of windows is installed?

**Comment by gisma** [comment]
@raff-k please check if this message is supressed now.

**Comment by raff-k** [comment]
Now, with `link2GI::linkGRASS7(x = RQGIS::dem, default_GRASS7 = c("C:/OSGeo4W64","grass-7.2.2","OSGeo4W64"), quiet = FALSE)` I got:

> gisdbase    d:/Users/qo23hel/AppData/Local/Temp/RtmpItoKKG 
> location    file2a1418b12132 
> mapset      PERMANENT 
> rows        117 
> columns     117 
> north       8935384 
> south       8931775 
> west        794599.1 
> east        798208.6 
> nsres       30.85 
> ewres       30.85 
> projection  +proj=utm +south +no_defs +zone=17 +a=6378137 +rf=298.257223563 +towgs84=0,0,0,0,0,0,0 +to_meter=1 
> $gisbase_GRASS
> [1] "C:/OSGeo4W64\\apps\\grass\\grass-7.2.2"
> 
> $version
> [1] "grass-7.2.2"
> 
> $type
> [1] "OSGeo4W64"
> 
> $installed
>                                  instDir     version installation_type
> 1 C:/OSGeo4W64\\apps\\grass\\grass-7.2.2 grass-7.2.2         OSGeo4W64


and with `link2GI::linkGRASS7(x = RQGIS::dem, default_GRASS7 = c("C:/OSGeo4W64","grass-7.2.2","OSGeo4W64"), quiet = TRUE)`, I still got:

> $gisbase_GRASS
> [1] "C:/OSGeo4W64\\apps\\grass\\grass-7.2.2"
> 
> $version
> [1] "grass-7.2.2"
> 
> $type
> [1] "OSGeo4W64"
> 
> $installed
>                                  instDir     version installation_type
> 1 C:/OSGeo4W64\\apps\\grass\\grass-7.2.2 grass-7.2.2         OSGeo4W64

Here, the `sessionInfo()`:

> R version 3.4.2 (2017-09-28)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
> [4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] RQGIS_1.0.2.9000 reticulate_1.4   link2GI_0.3-0    rgrass7_0.1-10   XML_3.98-1.9     sp_1.2-7     

... and the windows version is 10 (1703, Build 15063.850)

**Comment by gisma** [comment]
@raff-k  I probably misunderstood your issue request  However the returns of the function is not  thec onsole output you have mentioned  but  the intended response of the function.  It returns the bin and lib pathes of the linked versions for further use. Additionally it returns all versions that are found on the specified drive. 

You easily can put it in a variable and you will see nothing. If this is impossible or not wished by other reasons I would kindly ask you to open a new issue. I will integrate this in the github version . the next CRAN version is planned  in the second half of march. 
cheers Chris

**Comment by raff-k** [comment]
ah, okay, I thought that `linkGRASS7(...)`  "simply" creates a mapset without returning anything. `invisible(linkGRASS7(...))` would also work... 
I am asking me if there is the need to return the pathes, which I already gave as input for initialization. But for sure, on the other hand, if I do not know the pathes and just call `link2GI::linkGRASS7(x = RQGIS::dem)`, it is nice to get the information where GRASS GIS is located and which version has been taken :-)

However, I dont want to give the impression to nag here, I am totally happy about that package and especially about the `linkGRASS7()`-function :-)

**Comment by gisma** [comment]
Nice to hear that it is of use for you.  Just for clarification in your case it is for sure nonsense to return the passes that you gave as input, but there are a lot of cases especially if you want to use the command line instead of rgrass7 it makes sense.

**Comment by gisma** [comment]
@raff-k 
thanks again for the discussion. 
I have added the argument `returnPathes = FALSE`.
I would very much agree if you could test it
cheers Chris

**Comment by tim-salabim** [comment]
There is no e in paths.

**Comment by gisma** [comment]
depends on the dictionary :-P but thanks I will change it

**Comment by gisma** [comment]
change  `returnPathes = FALSE` to  `returnPaths = FALSE`

**Comment by gisma** [comment]
@raff-k close this issue please feel free to reopen it if necessary
