### ISSUE TITLE
Problem with findGRASS()

### ISSUE THREAD

**Issue by hbermeo** [r-spatial/link2GI#40]
Every time I do link = findGRASS () it generates NULL in addition to this long message.

> > Warning messages:
> 1: In system(paste0("cmd.exe /c TYPE \"", raw_GRASS[i], "\""), ignore.stdout = TRUE,  :
>   running command 'cmd.exe /c TYPE "C:\OSGeo4W64\bin\grass78.bat"' had status 1
> 2: In system(paste0("cmd.exe /c TYPE \"", raw_GRASS[i], "\""), ignore.stdout = TRUE,  :
>   running command 'cmd.exe /c TYPE "C:\OSGeo4W64\etc\preremove\grass.bat"' had status 1
> 3: In system(paste0("cmd.exe /c TYPE \"", raw_GRASS[i], "\""), ignore.stdout = TRUE,  :
>   running command 'cmd.exe /c TYPE "C:\Program Files\GRASS GIS 7.9\grass79.bat"' had status 1
> 4: In system(paste0("cmd.exe /c TYPE \"", raw_GRASS[i], "\""), ignore.stdout = TRUE,  :
>   running command 'cmd.exe /c TYPE "C:\Program Files\QGIS 3.6\bin\grass76.bat"' had status 1
> 5: In system(paste0("cmd.exe /c TYPE \"", raw_GRASS[i], "\""), ignore.stdout = TRUE,  :
>   running command 'cmd.exe /c TYPE "C:\Program Files\QGIS 3.6\etc\preremove\grass.bat"' had status 1
> 6: In system(paste0("cmd.exe /c TYPE \"", raw_GRASS[i], "\""), ignore.stdout = TRUE,  :
>   running command 'cmd.exe /c TYPE "C:\Users\Holger Bermeo\.qgis2\processing\grass_script.bat"' had status 1

**Comment by hbermeo** [comment]
I have GRASS GIS 7.9 installed on my pc

**Comment by gisma** [comment]
Thanks for pointing out. Weird this worked since the beginning. I have to check.

**Comment by gisma** [comment]
Pls check if it works now.

**Comment by hbermeo** [comment]
stays for hours and does nothing when doing
d = findGRASS ()
:(

**Comment by CamiloEr** [comment]
Same error here and it worked with @gisma solution.

@hbermeo try reinstall link2GI with:

```
install.packages("devtools")
devtools::install_github("r-spatial/link2GI", ref = "master")
```

**Comment by gisma** [comment]
@CamiloEr  thanks for the confirmation. 
@hbermeo did it work with the reinstallation of the github master branch?

**Comment by gisma** [comment]
Pls feel free to reopen
