### ISSUE TITLE
Issue with Spaces in Paths

### ISSUE THREAD

**Issue by ailich** [r-spatial/link2GI#42]
I've been testing out link2GI for using OTB from R, but I've run into a minor issue when there are spaces in the path names. I've found using `shQuote` around the input/output paths fixes the issue somewhat in that the output is written to a file, but throws an error because it fails to read into R (`retRaster=TRUE)`. I guess a workaround is to just use `retRaster=FALSE`, and then read in the output file on the next line with `brick`. (Rversion= 3.6.3, link2GI 0.4.3, raster 3.3-7)

```
library(raster)
library(link2GI)
OTB<- linkOTB(bin_OTB = "C://OTB-7.0.0-Win64/bin/")

#No Spaces
cmd<- parseOTBFunction(algo = "HaralickTextureExtraction", gili = OTB)
cmd$input<- "C://Users/socce/Desktop/test/my_raster.tif"
cmd$out<- "C://Users/socce/Desktop/test/out_raster.tif"
retStack<- runOTB(cmd,gili = OTB,quiet = FALSE)

#With Spaces
cmd<- parseOTBFunction(algo = "HaralickTextureExtraction", gili = OTB)
cmd$input<- "C://Users/socce/Desktop/test/with spaces/my_raster.tif"
cmd$out<- "C://Users/socce/Desktop/test/with spaces/out_raster.tif"
retStack<- runOTB(cmd,gili = OTB,quiet = FALSE) 
Error in .local(.Object, ...) : 

Error in .rasterObjectFromFile(x, objecttype = "RasterBrick", ...) : 
  Cannot create a RasterLayer object from this file. (file does not exist)
print(file.exists("C://Users/socce/Desktop/test/with spaces/out_raster.tif"))
FALSE

#With Spaces and shQuote
cmd<- parseOTBFunction(algo = "HaralickTextureExtraction", gili = OTB)
cmd$input<- shQuote("C://Users/socce/Desktop/test/with spaces/my_raster.tif")
cmd$out<- shQuote("C://Users/socce/Desktop/test/with spaces/out_raster.tif")
retStack<- runOTB(cmd,gili = OTB,quiet = FALSE)
Error in .local(.Object, ...) : 

Error in .rasterObjectFromFile(x, objecttype = "RasterBrick", ...) : 
  Cannot create a RasterLayer object from this file. (file does not exist)
print(file.exists("C://Users/socce/Desktop/test/with spaces/out_raster.tif"))
TRUE #Operation was successfully completed, but failed to load into R
retStack<- brick("C://Users/socce/Desktop/test/with spaces/out_raster.tif")

```

**Comment by gisma** [comment]
Thanks for pointing out. 
Yup I have to admit that it never come up to my mind that on the "user-path" side spaces and special characters could be a problem, because I alwas tell the studends "avoid it under all circumstances"... So not only spaces but extreme long or deep pathes and different code tables could rise problems. 
Nevertheless I have noted it and will try to fix it asap.

**Comment by gisma** [comment]
@ailich please check this fix. I just have testet it for your examples under Linux and for your example.

**Comment by ailich** [comment]
Awesome works perfectly now. Thanks!

**Comment by gisma** [comment]
Thanks also!
