### ISSUE TITLE
findGRASS()'s default searchLocation in Linux takes long to find grass

### ISSUE THREAD

**Issue by florisvdh** [r-spatial/link2GI#46]
Internally, `findGRASS()` does this in non-Windows systems:

```r
if (searchLocation=="default") searchLocation <- "/usr"
```

I suggest to set the default to `"/usr/bin"`. It works much faster. Are there cases where grass is installed in another folder than `/usr/bin`, when installed under `/usr`?

**Comment by gisma** [comment]
sorry have been for personal reasons a fairly long time off.
well probably only if one compile grass from scratch. in this case the user obviouslyknow how to adress this path.

**Comment by gisma** [comment]
have accepted the pull request
Thanks for contributing.

**Comment by florisvdh** [comment]
I think there may have been some confusion while accepting PR #45 + closing this issue. PR #45 solved #44 but not the suggestion made here. From your response, it seems you would welcome the idea. So I've made another PR #47 that tries to implement the request made here.
