### ISSUE TITLE
Update to CRAN

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/link2GI#55]
Hi @gisma (long time no see!),

do you plan to submit the current version to CRAN? I just spent an hour trying to debug what is wrong with `findGRASS()` on my computer and then discover that there is a fix on GitHub...

Best,
Jakub

**Comment by gisma** [comment]
Hi Jakub,
better we had spent the hour over a beer... 
I was planning to clean up `ink2GI` and make it ready for the `rgdal/rgrass` countdown.  But then there was not much time and to be honest I was not sure if this function is used at all after rstudio can be started from the `GRASS` shell.  
However, I still use it in many of my scripts and hence the dirty workaround.... 
Best Chris

**Comment by Nowosad** [comment]
My assumption is that a part of R users prefer to work in R for some time, and then jump to GRASS for a calculation or two. Thus I think your functions are helpful for them.

**Comment by gisma** [comment]
Probably you are right. I will update asap the workaround after checking for potential complications and overlaps between  `rgrass7` and `rgrass` .
