### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [r-spatial/link2GI#58]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by gisma** [comment]
Roger, thanks for pointing out  and the friendly reminder.  I am already struggling since a while I will finish it until University starts obver...do my best over the days.

**Comment by rsbivand** [comment]
[00check.log](https://github.com/r-spatial/link2GI/files/11139915/00check.log)
is a recent check log from running under `_SP_EVOLUTION_STATUS_=2` without retiring r-spatial packages (suggested in this package) on the library path. The minimal correction is to check that the package namespaces can be loaded, and if not, do not run those parts of the examples. It would be safer in the longer term to replace retiring r-spatial packages with active r-spatial/rspatial packages (see https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). So unfortunately, `0.5-2` didn't resolve this fully. The log points to an Rdata file in data, but I'm unsure whether this is the end of the matter.

**Comment by rsbivand** [comment]
Please also see https://r-spatial.org/r/2023/04/10/evolution3.html, fix best by June, latest October 2023.

**Comment by rsbivand** [comment]
Although this is almost done, when running CMD check without the retiring packages on the library path (as CRAN will be when `rgdal` is archived in October), I get: 
[00check.log](https://github.com/r-spatial/link2GI/files/11746647/00check.log). Reprex: without `rgdal` on the library path:
```
> load("rgb.rda")
Warning: namespace 'rgdal' is not available and has been replaced
by .GlobalEnv when processing object 'rgb'
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)
> ls()
[1] "rgb"
> str(rgb)
S4 class 'SpatRaster' [package "terra"]
```

**Comment by rsbivand** [comment]
@gisma Please re-open and fix the remaining problem. Consider dropping `rgrass7` too; it will be archived with `rgdal` which it uses.

**Comment by rsbivand** [comment]
@gisma rgrass7 was archived two days ago, so you should clear from Suggests: and elsewhere in the package, replacing with rgrass.

**Comment by gisma** [comment]
Thanks Roger!
I am working on it and hopefully fix in time
