### ISSUE TITLE
runOTB(): $ operator is invalid for atmoc vectors

### ISSUE THREAD

**Issue by konstantinengelmayer** [r-spatial/link2GI#64]
Hi, 
i am trying to run the `DimensionalityReduction` function of OTB with the `runOTB()` function.
```
pca = link2GI::parseOTBFunction("DimensionalityReduction",otb)
pca$input_in = rgbFN
pca$out=file.path(R.utils::getAbsolutePath(envrmt$path_stack),paste0("otb_pca_all_",basename(rgbFN)))
pca$progress="true"
pca$normalize="true"
rpc=link2GI::runOTB(pca, gili = otb$pathOTB, retRaster = TRUE , quiet = quiet)  
```
Executing  `runOTB()` leads to following error:
> Error in gili$pathOTB : $ operator is invalid for atomic vectors

`otb$pathOTB` gives [1] "C:\\\OTB-8.1.2-Win64\\\bin\\\\"

> sessionInfo()
R version 4.3.3 (2024-02-29 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)
Matrix products: default
locale:
[1] LC_COLLATE=English_Germany.utf8 
[2] LC_CTYPE=English_Germany.utf8   
[3] LC_MONETARY=English_Germany.utf8
[4] LC_NUMERIC=C                    
[5] LC_TIME=English_Germany.utf8    
time zone: Europe/Berlin
tzcode source: internal

**Comment by konstantinengelmayer** [comment]
Same error with runOTB() and LocalStatisticExtraction():
```
algo = link2GI::parseOTBFunction("LocalStatisticExtraction",otb)
algo$help =NULL
algo$input_in = pcaFn
algo$out=file.path(R.utils::getAbsolutePath(envrmt$path_stack),paste0("PCA","stat",k,"_",basename(pcaFn)))
algo$progress=1
algo$radius=k
algo$channel=1
rpc=link2GI::runOTB(algo, gili = otb$pathOTB, retRaster = TRUE , quiet = FALSE)
```
>Error in gili$pathOTB : $ operator is invalid for atomic vectors

**Comment by gisma** [comment]
Thanks for reporting. However agaon i can not reproduce the error. So far everything rin smooth on my wondows system. I will try later .

**Comment by gisma** [comment]
Finally I could tackle the error...

It is kind of related to issue #65

you should use `gili = otb` instead of `gili = otb$pathOTB`
I know it is from the example but if you already provide the path string and not the link list it will thwow the atomic vector error.
