### ISSUE TITLE
several issues with generated 000_setup.R

### ISSUE THREAD

**Issue by konstantinengelmayer** [r-spatial/link2GI#66]
Hey, 

there are some issues with the setup script. 

1.
```
root_folder = envimaR::alternativeEnvi(root_folder = root_folder,
                                   alt_env_id = alt_env_id,
                                   alt_env_value = alt_env_value,
                                   alt_env_root_folder = alt_env_root_folder)
```

The variables `alt_env_id`, `alt_env_value` and  `alt_env_root_folder` are not defined.

2.
```
envrmt = link2GI::setupProj(root_folder = root_folder,
                             folders = projectDirList,
                             fcts_folder = "src/functions/",
                             path_prefix = NULL,
                             libs = libs,
                             create_folders = TRUE)
```

The argument `path_prefix `is not an argument of the `setupProj()` function.

3.
```
raster::rasterOptions(tmpdir = dirs$path_tmp)
```

The variables `dir` is also not defined.

Also there is an issue with the name of the "configs" folder. The scripts refer to the "configs" folder but the folder is named "config".
Lastly the "master_config.yml" is generated inside of the src folder and not in the configs folder. There is also an issue with the name of the file "master-config-yml".

Thank you.

**Comment by gisma** [comment]
Thanks for the report.  Some of the adressed iussues are the result of dropping more or less deprecated `envimaR` approaches. There is no `alternativeEnvi` function any more. The corresponding variables `alt_env_id, alt_env_value, alt_env_root_folder` and `path_prefix` are consequently dropped too.
The variable 'dir' is the follow up of the former 'envrmt' Itowever I will check if it is more convininet to use the var `envrmt`

Finally i will fix the wrong name of the config folder and the correct name for the main yaml.

**Comment by gisma** [comment]
Hope this fixes the mention issues
