### ISSUE TITLE
Allow more than the drive letter

### ISSUE THREAD

**Issue by tnauss** [r-spatial/link2GI#7]
https://github.com/r-spatial/link2GI/blob/0f5a60ec412487dec1ec215bdebd5dee9a7b435d/R/grass7Control.R#L531

findGRASS() checks for drive letter on windows and returns an error if not only the driver letter but a top-level search path is provided for searchLocation (e.g. searchLocation = "C:/Users/Test/").

Suggested change: check drive letter with "grepl(paste0(LETTERS, ":", collapse="|"), searchLocation)"

Cheers
Thomas

**Comment by gisma** [comment]
Thanks for addressing
