### ISSUE TITLE
getrowGDALVer dosen't find the latest GDAL

### ISSUE THREAD

**Issue by CYglume** [r-spatial/link2GI#70]
Hi! I found a small bug in `getrowGDALVer()`,
https://github.com/r-spatial/link2GI/blob/6a5af051ae80ff79f7b63145ed117f155f4a294b/R/gdalControls.R#L328C1-L333C15

As it doesn't really catch the most recent version of GDAL, but only returned the final index in the loop.

**Comment by gisma** [comment]
Thanks for reporting and fixing
